-- shift-cl2 — Podcasts (Phase 1).
--
-- Async briefing-podcast pipeline: source (sesión / expediente / chat) →
-- Lexa scripts → ElevenLabs TTS → mp3 in GCS. Status polled by client.
--
-- Why a table (not a job queue): we need durable history per user,
-- audio asset references, and cost accounting. Status field doubles as
-- the worker state machine (queued → scripting → tts → encoding → ready).
-- Single-process API host runs the worker in-band; switch to a real
-- queue (BullMQ / Cloud Tasks) when we replicate.

create table if not exists podcasts (
  id              uuid primary key default gen_random_uuid(),
  user_id         uuid not null references auth.users(id) on delete cascade,

  -- What was turned into a podcast.
  source_type     text not null check (source_type in ('sesion','expediente','chat')),
  source_id       text not null,         -- legacy_session_id | numero | conversation_id
  title           text,                  -- generated by Lexa, editable later

  -- Generation params (locked at create time).
  voice_id        text not null,         -- whitelisted ElevenLabs voice
  duration_target_s int not null,        -- 90 | 180 | 300
  style           text not null default 'informativo' check (style in ('informativo','conversacional')),

  -- Worker state machine.
  status          text not null default 'queued'
                  check (status in ('queued','scripting','tts','encoding','ready','failed','cancelled')),
  progress        int  not null default 0,  -- 0-100, advisory only
  error           text,

  -- Outputs.
  script          jsonb,                 -- { title, segments:[{speaker,text,emotion?}] }
  audio_path      text,                  -- gs://bucket/userId/podcastId.mp3
  duration_actual_s int,
  cost_chars      int,                   -- ElevenLabs billed chars (cost telemetry)

  created_at      timestamptz not null default now(),
  finished_at     timestamptz
);

create index if not exists podcasts_user_idx        on podcasts(user_id, created_at desc);
create index if not exists podcasts_status_idx      on podcasts(status) where status in ('queued','scripting','tts','encoding');
create index if not exists podcasts_source_idx      on podcasts(source_type, source_id);

alter table podcasts enable row level security;

-- Owner-only. Service role bypasses RLS for the worker.
create policy podcasts_select_own on podcasts
  for select using (auth.uid() = user_id);
create policy podcasts_insert_own on podcasts
  for insert with check (auth.uid() = user_id);
create policy podcasts_update_own on podcasts
  for update using (auth.uid() = user_id);
create policy podcasts_delete_own on podcasts
  for delete using (auth.uid() = user_id);

-- Daily quota helper — used by the BFF before enqueuing. Counted against
-- 'created_at' window so a long-running gen doesn't double-count.
create or replace function podcasts_user_daily_count(uid uuid)
returns int
language sql
stable
as $$
  select count(*)::int
  from podcasts
  where user_id = uid
    and created_at > now() - interval '24 hours'
    and status not in ('failed','cancelled');
$$;
