-- 0023_workspace_assets.sql
--
-- Branded asset pipeline (carrusel, pptx, document, podcast) — replaces the
-- Gamma path for these surfaces. Adds three columns to workspace_nodes plus
-- the new asset types in the type-check constraint.
--
-- Why it lives on workspace_nodes (not a separate table):
--   • Each asset is FIRST CLASS on the canvas — user drags/positions it,
--     edits it slide-by-slide, comments on it. Treating it as another node
--     keeps the ReactFlow contract uniform.
--   • Slide history per slide (not per asset) is mandatory because the
--     editorial workflow is "regenerate slide 3 with this instruction" — we
--     need to store before/after on the SLIDE level so the user can roll
--     back surgically without losing edits to other slides.
--
-- Schema:
--   asset_metadata     — kind, export_url, gamma_url?, generation_id?,
--                        slides_count, generated_at, options, source.
--   asset_slides       — array of slide objects (idx, kind, eyebrow, headline,
--                        body, items?, columns?, alert?, meta?). Each slide
--                        is independently editable.
--   asset_slide_history — append-only audit log {slide_idx, before, after,
--                        instruction, edited_at, edited_by_user_id}. Bounded
--                        in practice to ~50 entries per asset (UI surfaces
--                        the last N).
--
-- Idempotent: re-running drops + recreates the constraint and uses
-- `add column if not exists`.

alter table workspace_nodes drop constraint if exists workspace_nodes_type_check;

alter table workspace_nodes
  add constraint workspace_nodes_type_check
  check (type in (
    'hoja',
    'note',
    'cite',
    'expediente_ref',
    'image',
    'document',
    'audio',
    -- Branded assets generated by atlasContentGenerator + htmlAssetRenderer:
    'carousel',       -- 1080x1080 social carousel (LinkedIn / IG / X)
    'pptx_asset',     -- 1920x1080 deck (replaces Gamma pptx flow)
    'docx_asset',     -- A4 multipage document (replaces Gamma document flow)
    'podcast_asset'   -- audio asset; reuses existing podcast pipeline
  ));

-- ─── Asset columns ───────────────────────────────────────────────────
-- Stored as jsonb so the shape can evolve without migrations and the
-- frontend can introspect each slide's `kind` to render the right
-- preview/edit UI.

alter table workspace_nodes
  add column if not exists asset_metadata jsonb not null default '{}'::jsonb;

alter table workspace_nodes
  add column if not exists asset_slides jsonb not null default '[]'::jsonb;

alter table workspace_nodes
  add column if not exists asset_slide_history jsonb not null default '[]'::jsonb;

-- Helpful index for "list assets in workspace" queries (cheap because most
-- workspaces have <10 nodes, but it future-proofs the surface).
create index if not exists workspace_nodes_asset_kind_idx
  on workspace_nodes ((asset_metadata->>'kind'))
  where type in ('carousel','pptx_asset','docx_asset','podcast_asset');

-- ─── RLS — already enabled on workspace_nodes by 0011_workspace.sql ─
-- The "ws_node_owner" policy gates SELECT/INSERT/UPDATE/DELETE by joining
-- workspace_nodes.workspace_id → workspaces.user_id = auth.uid(). The new
-- columns inherit those rules automatically (RLS is row-level, not column-
-- level), so no additional policy is needed. We re-affirm the policy here
-- so this migration is self-contained for ops review.
do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'workspace_nodes'
      and policyname = 'ws_node_owner'
  ) then
    -- This branch only fires in environments where 0011 wasn't applied;
    -- in production it's a no-op. Kept for parity with that migration.
    create policy "ws_node_owner" on workspace_nodes
      for all using (
        exists (
          select 1 from workspaces w
          where w.id = workspace_nodes.workspace_id
            and w.user_id = auth.uid()
        )
      ) with check (
        exists (
          select 1 from workspaces w
          where w.id = workspace_nodes.workspace_id
            and w.user_id = auth.uid()
        )
      );
  end if;
end $$;

-- ─── Storage bucket for branded assets ───────────────────────────────
-- Separate from `workspace-assets` (user-uploaded) and `shift-cl2-podcasts`
-- (audio). Branded assets are PDFs generated server-side; the bucket is
-- public-read because the export_url is shared with clients via LinkedIn
-- (carousel) or download buttons (pptx/docx).
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'cl2-assets',
  'cl2-assets',
  true,                           -- public read; writes are service-role only
  52428800,                       -- 50MB cap per file (PDF assets are <5MB usually)
  array[
    'application/pdf',
    'image/png','image/jpeg','image/webp'
  ]
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

-- Read policy: public (renders inline in browser via signed export_url).
-- Write policy: service-role only — the renderer service holds those creds,
-- never the client. We don't need a write policy for `authenticated` users.
do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'storage' and tablename = 'objects'
      and policyname = 'cl2_assets_public_read'
  ) then
    create policy "cl2_assets_public_read" on storage.objects
      for select using (bucket_id = 'cl2-assets');
  end if;
end $$;
